config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  @tasks = Task.all
  end 

  def show
    @task = Task.find(params[:id])
  end 

  def new
    @task = Task.new
  end 

  def create
    @task = Task.new(task_params)
    
    if @task.save
      flash[:success] = 'Taskが正常に保存されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Taskが保存されませんでした'
      render :new
    end 
  end 

  def edit
    @task = Task.find(params[:id])
  end 

  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit 
    end   
  end 

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end 
end

private

#strong parameter
def task_params
  params.require(:task).permit(:content)
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
 <div>
     <%= task %>
 </div>
 <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
    <%= yield %>
    </div> 
  </body>
    
</html>

app/views/tasks/edit.html.erb
<h1>id:<%= @task.id %>のタスク編集のページ</h1>
<%= form_with(model: @task, local: true) do |f| %>
<%= f.label :content, 'タスク' %>
<%= f.text_field :content %>
<%= f.submit '保存' %>
<% end %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.id, task %> : <%= task.content %></li>
  <% end %>
</ul>

<%= link_to '新タスク作成', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>
  <%= form_with(model:@task, local: true) do |f| %>
  
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
  <%= f.submit '保存' %>
  <% end %>
  
  <%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1> id: <%= @task.id %>のタスク詳細</h1>
  <p><%= @task.content %></p>
  
  <%= link_to '一覧に戻る', tasks_path %>
  <%= link_to 'このタスクを編集する', edit_task_path(@task) %>
  <%= link_to 'このタスクを削除する', @task, method: :delete, data: {confirm: '本当に削除してよろしいですか？'} %>
  